version: '3.8'

services:
  nodejsapp:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mssql
    environment:
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}

  mssql:
    build:
      context: .
      dockerfile: mssql.dockerfile
    environment:
      - ACCEPT_EULA=Y
     # - MSSQL_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - "5433:1433"
