version: '3.8'

services:
  nodejsapp:
    image: kelvinfernandess04/nodejsapp:latest
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mssql
    environment:
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}

  mssql:
    image: kelvinfernandess04/mssql:latest
    build:
      context: .
      dockerfile: mssql.dockerfile
    environment:
      - ACCEPT_EULA=Y
     # - MSSQL_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - type: volume
        source: mssql_data
        target: /var/opt/mssql/data
      - type: volume
        source: mssql_log
        target: /var/opt/mssql/log
      - type: volume
        source: mssql_secrets
        target: /var/opt/mssql/secrets
    ports:
      - "5433:1433"
    
volumes:
  mssql_data:
  mssql_log:
  mssql_secrets:

